apiVersion: apps/v1
kind: Deployment
metadata:
  name: impulse-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: impulse-app
  template:
    metadata:
      labels:
        app: impluse-app
    spec:
      containers:
      - name: impulse
        image: IMAGE_HERE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: impulse-app-svc
spec:
  selector:
    app: impulse-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
  type: LoadBalancer
